### ISSUE TITLE
Fails with asyncio exception on Mac

### ISSUE THREAD

**Issue by jackjansen** [adafruit/Adafruit_CircuitPython_BLE#102]
Installed the module (Python 3.7, MacOS 10.15) according to the instructions in the readme file. Installed in a virtual environment.

Tried to run the example code (again from the readme).

I get a RuntimeError from asyncio:

```
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    for entry in radio.start_scan(timeout=60, minimum_rssi=-80):
  File "/Users/jack/tmp/venv-ble/.env/lib/python3.7/site-packages/adafruit_ble/__init__.py", line 271, in start_scan
    active=active,
  File "/Users/jack/tmp/venv-ble/.env/lib/python3.7/site-packages/_bleio/adapter_.py", line 214, in start_scan
    self._scan_for_interval(scanner, self._SCAN_INTERVAL)
  File "/Users/jack/tmp/venv-ble/.env/lib/python3.7/site-packages/_bleio/adapter_.py", line 114, in await_bleak
    return future.result(timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 432, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/Users/jack/tmp/venv-ble/.env/lib/python3.7/site-packages/_bleio/adapter_.py", line 312, in _scan_for_interval
    await scanner.start()
  File "/Users/jack/tmp/venv-ble/.env/lib/python3.7/site-packages/bleak/backends/corebluetooth/scanner.py", line 47, in start
    await self._manager.wait_for_powered_on(0.1)
  File "/Users/jack/tmp/venv-ble/.env/lib/python3.7/site-packages/bleak/backends/corebluetooth/CentralManagerDelegate.py", line 106, in wait_for_powered_on
    await asyncio.wait_for(self.powered_on_event.wait(), timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py", line 416, in wait_for
    return fut.result()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/locks.py", line 293, in wait
    await fut
RuntimeError: Task <Task pending coro=<Event.wait() running at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/locks.py:293> cb=[_release_waiter(<Future pendi...5305c46d8>()]>)() at /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/tasks.py:366]> got Future <Future pending> attached to a different loop
```

**Comment by dhalbert** [comment]
I believe this was fixed by https://github.com/adafruit/Adafruit_Blinka_bleio/pull/21 or a following PR. Please re-open if it is still not working after you update all the dependencies.
