### ISSUE TITLE
got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by arslan437** [adafruit/Adafruit_CircuitPython_BLE#107]
I am using rapberry  4

```

pi@raspberrypi:~/tcodes/Adafruit_CircuitPython_BLE/examples $ python ble_current_time_service.py
Traceback (most recent call last):
  File "ble_current_time_service.py", line 15, in <module>
    radio.start_advertising(a)
  File "/home/pi/.local/lib/python3.7/site-packages/adafruit_ble/__init__.py", line 212, in start_advertising
    timeout=0 if timeout is None else timeout,
TypeError: start_advertising() got an unexpected keyword argument 'timeout'


```

**Comment by jpeponis** [comment]
I got this as well.
