### ISSUE TITLE
ble_lywsd03mmc_simpletest.py trigger Type error in BLE with 8.0.0-beta.0

### ISSUE THREAD

**Issue by dglaude** [adafruit/Adafruit_CircuitPython_BLE#172]
I am not sure this is a bug with this library or something in the BLE library...

But `ble_lywsd03mmc_simpletest.py` running on:
* Adafruit CircuitPython 8.0.0-beta.0 on 2022-08-18; Adafruit Feather Bluefruit Sense with nRF52840

Does trigger a Type error:
```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.
code.py output:
]0;🐍BLE:Reconnecting | code.py | 8.0.0-beta.0\Scanning...
Traceback (most recent call last):
  File "code.py", line 18, in <module>
  File "adafruit_ble/__init__.py", line 282, in start_scan
  File "adafruit_ble/advertising/__init__.py", line 319, in matches
  File "adafruit_ble/advertising/__init__.py", line 329, in matches_prefixes
TypeError: extra keyword arguments given
]0;🐍BLE:Off | 329@adafruit_ble/advertising/__init_ TypeError | 8.0.0-beta.0\
Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.
```

This is the line 18:
```
    for adv in ble.start_scan(Advertisement, timeout=5):
```

**Comment by tekktrik** [comment]
I can tackle this!

**Comment by dhalbert** [comment]
Ref https://github.com/adafruit/circuitpython/pull/6730
