### ISSUE TITLE
Can't import adafruit_ble library on ESP32 Feather V2

### ISSUE THREAD

**Issue by Zwettekop** [adafruit/Adafruit_CircuitPython_BLE#175]
I was following this guide: https://learn.adafruit.com/ble-hid-keyboard-buttons-with-circuitpython/overview
I copied all the code from the guide with thonny to my microcontroller. When running the code I get the error: 

```
Traceback (most recent call last):
  File "<stdin>", line 14, in <module>
  File "adafruit_ble/__init__.py", line 25, in <module>
ImportError: no module named '_bleio'
```
**When I run it in the interpreter and not in the code.py file the line doesn't crash!** Using other libraries is also not an issue. I can for instance use the neopixel library to program my onboard neopixel.

**Comment by Zwettekop** [comment]
I just found out that the ESP32 Feather V2 **doesn't support bluetooth** (_bleio module is not implemented yet)
It would be nice if they mentioned that bluetooth doesn't work on the main adafruit page though....
Right now it says:  "The ESP32 has both WiFi and Bluetooth Classic/LE support. That means it's perfect for just about any wireless or Internet-connected project."

Dissapointing. -20 bucks I guess.
