### ISSUE TITLE
apple notifications - soft device error

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_BLE#44]
I tried the ble_apple_notifications.py demo on a CPB with 5.0Beta.1 
this error occurred

```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-beta.1 on 2019-12-10; Adafruit Circuit Playground Bluefruit with nRF52840
>>> import ble_apple_notifications
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ble_apple_notifications.py", line 15, in <module>
  File "adafruit_ble/__init__.py", line 174, in start_advertising
_bleio.BluetoothError: Unknown soft device error: 0007
>>> 

````

same error on a feather_nRF52840 express
updated to 3.1.1 -- still same error

**Comment by dhalbert** [comment]
Which model of iPhone or iPad are you using?

**Comment by jerryneedell** [comment]
This was before I tried to connect.
I gave an iPhone 7 and an iPad pro

**Comment by jerryneedell** [comment]
Does this work for you?

**Comment by tannewt** [comment]
0007 is invalid parameter.

@jerryneedell can you try running it as code.py? There may be something that is being long lived. However, long living usually happens after an import finishes I believe.

**Comment by jerryneedell** [comment]
@tannewt same failure as code.py on feather_nrf52840_express

**Comment by jerryneedell** [comment]
I'm just puzzled what is different from my setup that yours.

**Comment by jerryneedell** [comment]
just to be sure, I tried entering the commands at the REPL -- same result
```

Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 5.0.0-beta.1 on 2019-12-10; Adafruit Feather nRF52840 Express with nRF52840
>>> 
>>> 
>>> import time
>>> import adafruit_ble
>>> from adafruit_ble.advertising.standard import SolicitServicesAdvertisement
>>> from adafruit_ble.services.apple import AppleNotificationService
>>> 
>>> radio = adafruit_ble.BLERadio()
>>> a = SolicitServicesAdvertisement()
>>> a.complete_name = "NotifyPlease"
>>> a.solicited_services.append(AppleNotificationService)
>>> radio.start_advertising(a)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ble/__init__.py", line 174, in start_advertising
_bleio.BluetoothError: Unknown soft device error: 0007
```

**Comment by tannewt** [comment]
I think this might be because of the new auto-scan response which adds a different complete name. Testing it now.

**Comment by tannewt** [comment]
It is more complicated than that. Still looking.
