### ISSUE TITLE
uuid module missing

### ISSUE THREAD

**Issue by jerryneedell** [adafruit/Adafruit_CircuitPython_BLE#7]
I am unable to test the ibeacon since the uuid.py module is missing 
```
Press any key to enter the REPL. Use CTRL-D to reload.
Adafruit CircuitPython 4.0.0-alpha.5-207-gf46ec0253 on 2019-01-22; Adafruit Feather nRF52840 Express with nRF52840
>>> 
>>> import ibeacon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "ibeacon.py", line 2, in <module>
ImportError: no module named 'adafruit_ble.uuid'
>>> import ibeacon
```

**Comment by jerryneedell** [comment]
FYI - teh ble_eddystone_test works well

**Comment by dhalbert** [comment]
The example in the doc is outdated. Use `from bleio import UUID` instead. Sorry about that. I updated the `examples/` but forgot about the examples in the code documentation. Will fix.

**Comment by jerryneedell** [comment]
Thank -- that works!s

**Comment by dhalbert** [comment]
reopening to remind me to fix the doc
